<?php

require_once dirname( dirname( __FILE__ ) ) . '\mail.php';

/**
 * Test class for Mail.
 * @covers Mail
 * Generated by PHPUnit on 2013-05-18 at 15:40:58.
 */
class MailTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @var Mail
	 */
	protected $mail;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp() {
		$this->mail = new Mail;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	public function tearDown() {}

	/**
	 * Test if an email is valid
	 * @covers Mail::is_email()
	 * @dataProvider mail_DataProvider
	 * @dataProvider other_mail_DataProvider
	 * @dataProvider commented_email_DataProvider
	 */
	public function testIs_mail( $mail, $expected, $sanitized) {
		$actual = $this->mail->is_mail( $mail );
		$this->assertEquals( $expected, $actual );
	}

	/**
	 * DataProvider for emails
	 * This function collect different email sets and merge them
	 * @return	array
	 */
	public function mail_DataProvider() {
		$return = array();

		// examples from wikipedia
		// valid email adresses
		$valid_emails = array(
			array(  'niceandsimple@example.com', true,
					'niceandsimple@example.com' ),

			array(  'very.common@example.com', true,
					'very.common@example.com' ),

			array(  'a.little.lengthy.but.fine@dept.example.com', true,
					'a.little.lengthy.but.fine@dept.example.com' ),

			array(  'disposable.style.email.with+symbol@example.com', true,
					'disposable.style.email.with+symbol@example.com' ),

			array(  'user@[fc00:2001:db8:1ff::a0b:dbd0]', true,
					'user@[fc00:2001:db8:1ff::a0b:dbd0]' ),

			array(  '"much.more unusual"@example.com', true,
					'"much.more unusual"@example.com' ),

			array(  '"very.unusual.@.unusual.com"@example.com', true,
					'"very.unusual.@.unusual.com"@example.com' ),

			array(  'postbox@com', true,
					'postbox@com' ), //top-level domains are valid hostnames

			array(  'admin@mailserver1', true,
					'admin@mailserver1' ), //local domain name with no TLD

			array(  '!#$%&\'*+-/=?^_`{}|~@example.org', true,
					'!#$%&\'*+-/=?^_`{}|~@example.org' ),

			array(  '" "@example.org', true,
					'" "@example.org' ), //space between the quotes

			array(  '"very.(),:;<>[]\".VERY.\"very@\\ \"very\".unusual"@strange.example.com', true,
					'"very.(),:;<>[]\".VERY.\"very@\\ \"very\".unusual"@strange.example.com' ),

			array(  '"()<>[]:,;@\\\"!#$%&\'*+-/=?^_`{}| ~.a"@example.org', true,
					'"()<>[]:,;@\\\"!#$%&\'*+-/=?^_`{}| ~.a"@example.org' ),
		);

		// invalid email adresses
		// sanitazion will fail
		$invalid_emails = array(
			array( 'Abc.example.com',                       false, '' ),
			array( 'A@b@c@example.com',                     false, '' ),
			array( 'a"b(c)d,e:f;g<h>i[j\k]l@example.com',   false, '' ),
			array( 'just"not"right@example.com',            false, '' ),
			array( 'this is"not\allowed@example.com',       false, '' ),
			array( 'this\ still\"not\\allowed@example.com', false, '' ),
		);

		$return = array_merge( $return, $valid_emails );
		$return = array_merge( $return, $invalid_emails );

		return $return;
	}

	/**
	 * DataProvider for special mails
	 * @return array
	 */
	public function other_mail_DataProvider() {
		return array(
			// two @ signs; not escaped @ sign
			array( 'john@smith@example.com',                            false, '' ),
			array( 'john\@smith@example.com',                           true, '' ),
			// dot period; dots at start and/or end
			array( 'too..much...dots....@example.org',                  false, '' ),
			array( '.local.part.should.not.start.with.dot@example.org', false, '' ),
			array( 'local.part.should.not.end.with.dot.@example.org',   false, '' ),
			array( 'john-doe@.should.not.start.with.dot.org',           false, '' ),
			array( 'john-doe@should.not.end.with.dot.org.',             false, '' ),
			// punycode
			array( 'john-doe@Ümlaut-domän.cöm',                         true, '' ),
			array( 'john-doe@ümlaut-domän.cöm',                         true, '' ),
			array( 'john-doe@Ümlaut?domän.com',                         false, '' ),
			// too long label
			array( 'hans.klein@to.longlable123456789012345678901234567890123456789012345678901234567890.long.lable', false, '' ),
		);
	}

	/**
	 * DataProvider for commented emails
	 * @return	array
	 */
	public function commented_email_DataProvider() {
		return array(
			array( 'jo.sm(commentedemail)@example.com', true, 'jo.sm@example.com' ), // comment at start of local part
			array( '(commentedemail)jo.sm@example.com', true, 'jo.sm@example.com' ), // comment at end of local part
			array( 'jo.sm@(commentedemail)example.com', true, 'jo.sm@example.com' ), // comment at start of domain
			array( 'jo.sm@example.com(commentedemail)', true, 'jo.sm@example.com' ), // comment at end of domain

			// comments with space, same as above
			array( 'jo.sm(commented email)@example.com', true, 'jo.sm@example.com' ),
			array( '(commented email)jo.sm@example.com', true, 'jo.sm@example.com' ),
			array( 'jo.sm@(commented email)example.com', true, 'jo.sm@example.com' ),
			array( 'jo.sm@example.com(commented email)', true, 'jo.sm@example.com' ),

			// invalid comments
			array( 'jo(commentedemail).sm@example.com',  false, 'jo.sm@example.com' ),
			array( 'jo.sm@example(commentedemail).com',  false, 'jo.sm@example.com' ),
			array( 'jo(commented email).sm@example.com', false, 'jo.sm@example.com' ),
			array( 'jo.sm@example(commented email).com', false, 'jo.sm@example.com' ),
		);
	}

}

